version: '3'
services:
  rocketmq-namesrv:
    image: apache/rocketmq:4.9.4
    restart: always
    container_name: rocketmq-namesrv
    ports:
    - 9876:9876
    volumes:
    - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  rocketmq-broker:
    image: apache/rocketmq:4.9.4
    restart: always
    container_name: rocketmq-broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/home/rocketmq/rocketmq-4.9.4/conf/broker.conf
    command: sh mqbroker -n rocketmq-namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - rocketmq-namesrv
      
  rocketmq-console:
    image: styletang/rocketmq-console-ng
    restart: always
    container_name: rocketmq-console
    ports:
    - 8080:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
    - rocketmq-namesrv
