version: '3.7'
services:
    sqlserver1:
        container_name: ricky-mssql
        image: mcr.microsoft.com/mssql/server:2017-latest
        restart: always
        ports: 
          - "1433:1433"
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes:
          - ms_sql_system:/var/opt/mssql/
          - ms_sql_data:/var/opt/sqlserver/data
          - ms_sql_log:/var/opt/sqlserver/log
          - ms_sql_backup:/var/opt/sqlserver/backup

volumes:
  ms_sql_system:
    driver: local
  ms_sql_data:
    driver: local
  ms_sql_log:
    driver: local
  ms_sql_backup:
    driver: local