version: "2"

volumes:
  nextcloud:

services:
  app:
    image: nextcloud:stable-fpm
    restart: always
    links:
      - ricky-mysql
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=ljz-ljz001
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=ricky-mysql

  web:
    image: nginx
    restart: always
    ports:
      - 10911:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
